project:
  type: website
  output-dir: docs

website:
  title: "Blog Project"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: #pulse
      light: pulse
      dark: vapor
    #css: [pulse, theme-dark.scss] #styles.css



